/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCaixa;
import controller.ControllerSangria;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import model.ModelCaixa;
import model.ModelSangria;
import util.BLMascaras;

/**
 *
 * @author GABRIELA
 */
public class ViewSangria extends javax.swing.JFrame {
ModelSangria modelSangria = new ModelSangria();
ControllerSangria controllersangria = new ControllerSangria();
BLMascaras blm = new BLMascaras();
ModelCaixa modelCaixa = new ModelCaixa();
ControllerCaixa controllerCaixa = new ControllerCaixa();
    /**
     * Creates new form ViewSangria
     */
    public ViewSangria() {
        initComponents();
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aaa = new javax.swing.JTextField();
        jlValorTotal4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sangria");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-selecionado-50.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Digite o Valor da Sangria:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cofrinho-50.png"))); // NOI18N

        aaa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                aaaFocusLost(evt);
            }
        });
        aaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aaaKeyTyped(evt);
            }
        });

        jlValorTotal4.setText("R$:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlValorTotal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aaa, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(136, 136, 136))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValorTotal4)
                    .addComponent(aaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //pegar total_movimentacoes/caixa e fazer verificacao
        ModelCaixa modelo = controllerCaixa.getUltimoIdController(modelCaixa);
        ModelCaixa movimentacao = controllerCaixa.getUltimaMovimentacaoController(modelCaixa);
        ModelCaixa movimentacaoCaixa = controllerCaixa.getUltimaMovimentacaoCaixaController(modelCaixa);
        ModelCaixa movimentacaoDinheiroSangria = controllerCaixa.getUltimoDinheiroSangriaController(modelCaixa);
        ModelCaixa movimentacaoCredito = controllerCaixa.getUltimoCreditoController(modelCaixa);
        ModelCaixa movimentacaoDebito = controllerCaixa.getUltimoDebitoController(modelCaixa);
        ModelCaixa movimentacaoDinheiro = controllerCaixa.getUltimoDinheiroController(modelCaixa);
        float DinheiroSangria = movimentacaoDinheiroSangria.getCaixa_sangria_dinheiro();
        float sangria = Float.parseFloat(aaa.getText());
        
        
        if(DinheiroSangria < sangria){
         JOptionPane.showMessageDialog(this, "Sangria maior que valor disponível em caixa", "Atenção", JOptionPane.ERROR_MESSAGE );
            aaa.setText(0+"");
        
        } else{
        //somar sangria em caixa e atualiza
        
            //setar fk caixa
            modelSangria.setFk_caixa(modelo.getPk_caixa());
            
            //setar Total Movimentação em tabela caixa
            modelo.setTotal_Movimentacoes(blm.arredondamentoComPontoDuasCasas(movimentacao.getTotal_Movimentacoes()));
        
            //setar Total Sangria em tabela caixa 
            modelo.setTotal_Caixa_sangria((movimentacaoCaixa.getTotal_Caixa_sangria()+ (float) sangria));
            
            //setar Débito
            modelo.setTotal_Debito(blm.arredondamentoComPontoDuasCasas(movimentacaoDebito.getTotal_Debito()));
            
            //setar Dinheiro
            modelo.setTotal_Dinheiro(blm.arredondamentoComPontoDuasCasas(movimentacaoDinheiro.getTotal_Dinheiro()));
            
            //setar Crédito
            modelo.setTotal_Credito(blm.arredondamentoComPontoDuasCasas(movimentacaoCredito.getTotal_Credito()));
            
            //setar dinheiro disponivel no caixa em tabela caixa
            modelo.setCaixa_sangria_dinheiro(movimentacaoDinheiroSangria.getCaixa_sangria_dinheiro() - sangria);
            
             
            boolean salvaTotal = controllerCaixa.atualizar1CaixaController(modelo);
         
        //setar valor sangria
         modelSangria.setValor_sangria(Double.parseDouble(aaa.getText()));
       
        //setar data de sangria
         
        LocalDate locald = LocalDate.now();
        java.sql.Date sqlDate = java.sql.Date.valueOf(locald); 
        modelSangria.setDate_sangria(sqlDate);
        
         //salvar no banco  
       int codigoVenda = 0;    
        codigoVenda = controllersangria.salvarSangriaController(modelSangria);
              if(codigoVenda >0){
                    JOptionPane.showMessageDialog(this, "Sangria Salva");
                    dispose();
                
                }else{
                    JOptionPane.showMessageDialog(this, "Erro", "Erro", JOptionPane.ERROR_MESSAGE);
                }
         
       }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aaaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aaaFocusLost
       aaa.setText(blm.converterVirgulaParaPonto(aaa.getText()));
       try{
        aaa.setText(blm.arredondamentoComPontoDuasCasasString(Float.parseFloat(aaa.getText())));
       }catch(Exception e){}
    }//GEN-LAST:event_aaaFocusLost

    private void aaaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aaaKeyTyped
        
        String caracteres="0987654321.,";
                if(!caracteres.contains(evt.getKeyChar()+"")){
                    evt.consume();
                    JOptionPane.showMessageDialog(this, "Letras e caracteres Especiais não são válidos", "Atenção", JOptionPane.ERROR_MESSAGE );
                }
    }//GEN-LAST:event_aaaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSangria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSangria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSangria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSangria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSangria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aaa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlValorTotal4;
    // End of variables declaration//GEN-END:variables
}
